### ISSUE TITLE
[bug]面板获取报错

### ISSUE THREAD

**Issue by Dnyo666** [ZZZure/ZZZ-Plugin#12]
![image](https://github.com/user-attachments/assets/fa5d2d63-0bc2-4e90-82fd-7a004e145c4e)
![image](https://github.com/user-attachments/assets/3a63ca27-ab1a-45e7-9721-188db5e5c692)

**Comment by bietiaop** [comment]
这不是报错哈，这个功能还在写，这是输出的数据

**Comment by Dnyo666** [comment]
好的，加油！

**Comment by bietiaop** [comment]
已经做好了哈
