### ISSUE TITLE
获取cookie失败，请确认绑定了cookie或者查询的UID是否与cookie对应，请确认bot所使用的是绝区零UID

### ISSUE THREAD

**Issue by wzwei1990** [ZZZure/ZZZ-Plugin#13]
米友社有两个游戏原神和绝区零  输入ck就绑定了两个uid 是因为这个原因报错吗  怎么只绑定绝区零

**Comment by bietiaop** [comment]
请确认扫码登录后，机器人返回的绑定UID中有 绝区零。如果没有，请确认：
1. 确保使用的是Miao-Yunzai或者Trss-Yunzai。
2. 请确保yunzai本体保持最新（最新版才支持绑定绝区零）。
3. 请确保米游社账号同时绑定了原神和绝区零。

**Comment by wzwei1990** [comment]
确定米社游绑定了原神和绝区零&nbsp; 扫码登录返回了有绝区零 但查询我的ck只有原神uid



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 中午1:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZZZure/ZZZ-Plugin] 获取cookie失败，请确认绑定了cookie或者查询的UID是否与cookie对应，请确认bot所使用的是绝区零UID (Issue #13)




 
请确认扫码登录后，机器人返回的绑定UID中有 绝区零。如果没有，请确认：
  
确保使用的是Miao-Yunzai或者Trss-Yunzai。
 
请确保yunzai本体保持最新（最新版才支持绑定绝区零）。
 
请确保米游社账号同时绑定了原神和绝区零。

**Comment by bietiaop** [comment]
加群973399270发送截图我看看

**Comment by wzwei1990** [comment]
扫码登录可以了 手动输入的不可以

**Comment by wzwei1990** [comment]
我扫码可以了 但别人不可以 奇怪

**Comment by bietiaop** [comment]
刷新抽卡记录依赖sk，因此需要扫码绑定，直接发送ck是不可以的。

**Comment by wzwei1990** [comment]
必须绑定原神吗

**Comment by yysforget** [comment]
绑定的是米游社账号,米游社里有原神就会绑定
只有绝区零也能用

**Comment by bietiaop** [comment]
只有有原神的才能刷新抽卡记录，逍遥插件是这样写的。其他的有绝区零就可以用

**Comment by wzwei1990** [comment]
嗯 现在就是抽卡的那部分命令报这个错 我试着让他绑定原神再试试

**Comment by kissnavel** [comment]
关联#22

**Comment by Alex6357** [comment]
之前一切正常，现在更新抽卡链接又出现这个报错了

**Comment by Alex6357** [comment]
> 之前一切正常，现在更新抽卡链接又出现这个报错了

没事了，更新后解决（
