### ISSUE TITLE
在QQBot环境使用%卡片提示请求数据过大

### ISSUE THREAD

**Issue by OvertimeBunny** [ZZZure/ZZZ-Plugin#18]
![](https://telegraph-image-buv.pages.dev/file/ada63e352d8fa9d32c4d1.png)

**Comment by bietiaop** [comment]
尝试在配置文件里将分辨率调低

**Comment by bietiaop** [comment]
在 zzz 插件目录/config/config.yaml 里将渲染精度调整为 50～100 之间的数字试试

**Comment by kissnavel** [comment]
渲染调到50或者更低看看，图片太大了

**Comment by Denfenglai** [comment]
二臂

**Comment by Denfenglai** [comment]
昨天不是说了调渲染精度怎么还交issue

**Comment by Admilkk** [comment]
原来是什么逆天渲染精度

**Comment by peterliangaaa** [comment]
你🐎怎么生了你这个脑缺玩意，听不懂人话
