### ISSUE TITLE
用抽卡链接直接获取抽卡记录

### ISSUE THREAD

**Issue by Alex6357** [ZZZure/ZZZ-Plugin#20]
现在直接发送绝区零的抽卡链接回复链接复制错误或已失效，但确认链接可以用在比如绝区零工坊等其他获取程序。不确定是否是miao-plugin的功能冲突。

**Comment by bietiaop** [comment]
已知问题，因为抽卡记录要以 uid 形式存储，在没有绑定cookie的情况下暂时无法获取 uid。建议使用 扫码登录。这个 bug 以后会修复。

**Comment by kissnavel** [comment]
国服：参考上一条comment
国际服：目前抽卡记录只支持国服，不支持国际服

**Comment by bietiaop** [comment]
已修复
