### ISSUE TITLE
无法更新抽卡记录，猜测原因只玩了绝区零

### ISSUE THREAD

**Issue by lin-junliang** [ZZZure/ZZZ-Plugin#22]
![image](https://github.com/user-attachments/assets/af8364ad-d3c6-43db-a023-91a68ceb1109)
![image](https://github.com/user-attachments/assets/3b3b859f-ca7f-4326-a07a-c50ffef450c5)
大部分账号都可以正常更新抽卡记录，少部分不行（已知2个），特征是这个账号是专门创建来玩绝区零的，没有原神的uid，不知道是否有关联？

**Comment by kissnavel** [comment]
关联#13
