### ISSUE TITLE
目前绝区零有些攻略是三测的，希望能筛选下

### ISSUE THREAD

**Issue by devil233-ui** [ZZZure/ZZZ-Plugin#23]
举例，妮可的第一个攻略（来自新艾利都快讯），与公测版本差距不小，但又没有足以区分的标志（最后更新时间）等，很容易造成误导。

可以的话，希望能直接对mys标题加个关键词过滤会好些？

**Comment by bietiaop** [comment]
后面加上默认攻略设置

**Comment by bietiaop** [comment]
不过建议专业的事情交给专业的人来做。攻略图鉴建议使用 readme 中推荐的哈。

**Comment by ZM-J** [comment]
这个三测攻略和公测攻略有什么可区分的标志吗？

**Comment by ZM-J** [comment]
以及，如果有更好的、更高质量的攻略源，也欢迎提供

**Comment by devil233-ui** [comment]
> 这个三测攻略和公测攻略有什么可区分的标志吗，除了攻略发布的时间之外？

我能想到的只有对标题关键词进行正则了

> 以及，如果有更好的、更高质量的攻略源，也欢迎提供

好的，我会留意

**Comment by devil233-ui** [comment]
> 以及，如果有更好的、更高质量的攻略源，也欢迎提供

来了。
[这位](https://m.miyoushe.com/dby/#/collection/2374527)是原铁时期的老手了，质量一直很稳定

[这位](https://m.miyoushe.com/dby/#/collection/2723586)虽然是新人，但潜力很大

**Comment by ZM-J** [comment]
> > 以及，如果有更好的、更高质量的攻略源，也欢迎提供
> 
> 来了。 [这位](https://m.miyoushe.com/dby/#/collection/2374527)是原铁时期的老手了，质量一直很稳定
> 
> [这位](https://m.miyoushe.com/dby/#/collection/2723586)虽然是新人，但潜力很大

第一位貌似不是分角色做的（一个角色单独开一个贴子），起码适配就需要重新弄（[这里](https://www.miyoushe.com/dby/collection/2716049)倒是有分角色的，但是不知道为啥就三个）

第二位倒是好加

**Comment by ZM-J** [comment]
那么新艾利都快讯的[攻略](https://www.miyoushe.com/dby/collection/2712859)里面那些未标注三测版本的内容（如艾莲、11号等）是否是具有时效性的？

**Comment by devil233-ui** [comment]
> > > 以及，如果有更好的、更高质量的攻略源，也欢迎提供
> > 
> > 
> > 来了。 [这位](https://m.miyoushe.com/dby/#/collection/2374527)是原铁时期的老手了，质量一直很稳定
> > [这位](https://m.miyoushe.com/dby/#/collection/2723586)虽然是新人，但潜力很大
> 
> 第一位貌似不是分角色做的（一个角色单独开一个贴子），起码适配就需要重新弄（[这里](https://www.miyoushe.com/dby/collection/2716049)倒是有分角色的，但是不知道为啥就三个）

> 第二位倒是好加

弄合集应该是因为太多了图省事（）但之后倒是应该会分开了吧。

> 那么新艾利都快讯的[攻略](https://www.miyoushe.com/dby/collection/2712859)里面那些未标注三测版本的内容（如艾莲、11号等）是否是具有时效性的？

没问题的，发布时间在公测后的基本都ok，事实上情报站也都收录了
https://baike.mihoyo.com/zzz/wiki/content/180/detail?mhy_presentation_style=fullscreen
https://baike.mihoyo.com/zzz/wiki/content/177/detail?mhy_presentation_style=fullscreen
