### ISSUE TITLE
扫码登陆超时

### ISSUE THREAD

**Issue by wzwei1990** [ZZZure/ZZZ-Plugin#24]
扫码登陆超时

**Comment by wzwei1990** [comment]
![bd6ebcc0cf13673b8cb1bc17e5b9ab6](https://github.com/user-attachments/assets/4cc9c640-467d-4cc0-8b29-7f36c7941041)

**Comment by yusheng929** [comment]
逍遥插件问题，不去看逍遥插件的issue，反而跑到绝区零插件问扫码登录

**Comment by wzwei1990** [comment]
逍遥插件都没有issue 去哪看

**Comment by yusheng929** [comment]
你🐎，你搜都不搜就说没有，你怎么这么逆天，眼睛不好可以捐了
https://github.com/ctrlcvs/xiaoyao-cvs-plugin/issues/150
