### ISSUE TITLE
面板报错问题

### ISSUE THREAD

**Issue by gggssepgf** [ZZZure/ZZZ-Plugin#31]
群友在使用  %猫又面板  的时候bot后台报错，但是很奇怪的是，我用自己的账号测试又不会有问题
![QQ_1722176421265](https://github.com/user-attachments/assets/b3934ebc-db2d-479b-b98f-25d31af6eb79)

**Comment by bietiaop** [comment]
到 `zzz插件目录/data/panel/` 找到他的 uid 对应的 json 文件删除，让他刷新面板试试。

**Comment by gggssepgf** [comment]
> 到 `zzz插件目录/data/panel/` 找到他的 uid 对应的 json 文件删除，让他刷新面板试试。
刚刚测试还是一样的报错信息

**Comment by bietiaop** [comment]
更新试试

**Comment by bietiaop** [comment]
更新插件试试

**Comment by gggssepgf** [comment]
测试没问题了，发现好像是群友的猫又没带驱动盘导致的
