### ISSUE TITLE
米游社账号绑定多个uid时无法切换uid

### ISSUE THREAD

**Issue by mulancha** [ZZZure/ZZZ-Plugin#33]
一个cookie里读出来了两个uid，但切换到第二个uid更新面板时会提示这个uid没有绑定cookie

**Comment by kissnavel** [comment]
发下#uid的图片看看，后台日志呢

**Comment by mulancha** [comment]
我试了下微信小程序和小黑盒都是可以正常使用两个uid的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月30日(周二) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZZZure/ZZZ-Plugin] 米游社账号绑定多个uid时无法切换uid (Issue #33)




 
发下#uid的图片看看，后台日志呢

**Comment by mulancha** [comment]
![IMG_20240730_105110](https://github.com/user-attachments/assets/9da133a5-ac45-45c7-b495-c53e2f28137f)
![Image_1722307961674](https://github.com/user-attachments/assets/6544ae15-9175-4bdf-ac33-a86d7c330806)

**Comment by bietiaop** [comment]
我还没见过多个账号的情况，你这是官服和B服绑在一个米游社账号吗？加QQ群私聊一下

**Comment by bietiaop** [comment]
已修复
