### ISSUE TITLE
绑定uid显示暂无uid信息

### ISSUE THREAD

**Issue by OriginElysia** [ZZZure/ZZZ-Plugin#34]
已通过yunzai扫码登录过米游社，自动识别了原神和星铁uid，但zzz没有识别
随后手动使用%绑定，然后使用%uid查看显示为无uid信息
![image](https://github.com/user-attachments/assets/f05ce6a0-846a-40ea-89fb-be69df182292)
此时，使用其他功能会提示：尚未绑定cookie，请先绑定cookie
同时，在panel文件中也没有该uid的JSON文件

**Comment by OriginElysia** [comment]
uid无误，且米游社zzz的信息均为公开状态

**Comment by kissnavel** [comment]
#刷新ck

**Comment by bietiaop** [comment]
首先你要确保 yunzai 为最新
其次 如果你的崽是 trss，确保 genshin 插件为最新
如果上面两个都更新后再重新扫码登录或刷新 ck
再看看有没有自动绝区零 uid

**Comment by OriginElysia** [comment]
是miao云崽的，不过奇怪的是，扫码了cookie能用
#刷新ck却提示
请求异常：登录状态失效，请重新登录

**Comment by bietiaop** [comment]
zzz 没有识别说明要么本体要么 genshin 插件不是最新

**Comment by bietiaop** [comment]
你更新一下试试

**Comment by OriginElysia** [comment]
都是git拉取到最新的，感觉是miao云崽那边有问题了，扫码只有半成功状态

**Comment by bietiaop** [comment]
半成功？什么意思？

**Comment by OriginElysia** [comment]
就是米游社已经提醒新设备登录了，但是机器人那边没回应扫码成功，直到超时

**Comment by bietiaop** [comment]
看下逍遥插件的 issue，有解决方法。

**Comment by OriginElysia** [comment]
解决了，感谢
