### ISSUE TITLE
查看面板时返回消息为{}，查看日志显示变成了先发消息后渲染

### ISSUE THREAD

**Issue by YuapXc** [ZZZure/ZZZ-Plugin#36]
更新了zzz-plugin ad0e156最新版后，获取角色面板返回消息为{}，日志显示先发出了消息后处理渲染
![7470ba9c614d6b9d110a7d11c9d51ea9](https://github.com/user-attachments/assets/06b48c8e-50bf-492c-b650-12109bbd679d)

**Comment by YuapXc** [comment]
![43b7d0baac6f271e9f35790e98d2fc2c](https://github.com/user-attachments/assets/5f748b39-56bc-4465-aab5-d0112b3b5540)
这是聊天界面

**Comment by bietiaop** [comment]
修复了，更新试试

**Comment by YuapXc** [comment]
更新功能正常了，谢谢佬
