### ISSUE TITLE
【建议】增加米游社自动签到功能

### ISSUE THREAD

**Issue by mengluo04** [ZZZure/ZZZ-Plugin#37]

**Comment by kissnavel** [comment]
签到另有插件实现

**Comment by mengluo04** [comment]
> 签到另有插件实现

请问插件地址是？

**Comment by kissnavel** [comment]
> > 签到另有插件实现
> 
> 请问插件地址是？

yunzai或其它bot有很多，找一下就有。
如懒得找又想用yunzai，点我主页。与本仓库无关，自行选择是否使用。

**Comment by mengluo04** [comment]
> > > 签到另有插件实现
> > 
> > 
> > 请问插件地址是？
> 
> yunzai或其它bot有很多，找一下就有。 如懒得找又想用yunzai，点我主页。与本仓库无关，自行选择是否使用。

OK,现在装了nb2的，看yunzai的miao-plus里面有原神的签到，想着能不能一起，不用单独开一个服务
