### ISSUE TITLE
【功能建议】添加配置设置是否允许群聊发送和获取抽卡记录

### ISSUE THREAD

**Issue by mengluo04** [ZZZure/ZZZ-Plugin#38]
不使用逍遥插件的情况下只能私聊发送抽卡链接，不是很方便，看了yunzai本体和插件的代码，云崽是直接通过消息类型设置的isPrivate，本插件在收到获取抽卡链接时使用isPrivate做了强制判断。
希望可以动态配置是否允许群聊发送抽卡，应该不存在什么风险，authkey目前的应用场景也就是查看抽卡记录
或者能否直接把抽卡地址拼接在指令后面，比如：%更新抽卡记录 https://public-operation-hk4e.mihoyo.com/xxx?authkey=xxx

**Comment by bietiaop** [comment]
直接把抽卡地址拼接在指令后面是没法做到的，还是要提醒使用者使用风险的

**Comment by bietiaop** [comment]
更新插件后在锅巴插件里可以进行快捷设置，如果没有锅巴插件，你可以参考 `defSet` 文件夹下的 `gacha.yaml` 对 `config` 文件夹下的 `gacha.yaml` 进行修改。
<img width="1548" alt="image" src="https://github.com/user-attachments/assets/759dbbe5-f3e7-426d-975b-9d7b4f5ff854">

**Comment by mengluo04** [comment]
> 更新插件后在锅巴插件里可以进行快捷设置，如果没有锅巴插件，你可以参考 `defSet` 文件夹下的 `gacha.yaml` 对 `config` 文件夹下的 `gacha.yaml` 进行修改。 <img alt="image" width="1548" src="https://private-user-images.githubusercontent.com/43831609/354887397-759dbbe5-f3e7-426d-975b-9d7b4f5ff854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjA1MTYsIm5iZiI6MTcyMjc2MDIxNiwicGF0aCI6Ii80MzgzMTYwOS8zNTQ4ODczOTctNzU5ZGJiZTUtZjNlNy00MjZkLTk3NWItOWQ3YjRmNWZmODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA4MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMTcwNTQzMDg5ZmFiNGUxZTY3N2YwZjk3ZWIxMWYwYTdmODA1ZmJhYjhkZTY1OGU1NWU0NmM3N2FiMmZlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-1UZe5RChc7rqEc3XSSk9Fj_9TuGgv2jTez3g-IPkbo">

好的，已更新并验证成功，多谢
