### ISSUE TITLE
[Bug] 锅巴插件修改深渊冷却时候的设置保存不成功，后台报错

### ISSUE THREAD

**Issue by Xbaishu** [ZZZure/ZZZ-Plugin#39]
[abyss] 格式错误 Error: ENOENT: no such file or directory, open 'F:\msys64\home\Administrator\TRSS_AllBot\Miao-Yunzai\plugins\ZZZ-Plugin\defSet\abyss.yaml'

经查询，该文件表示不存在，也不在仓库对应位置中，疑似文件忘记创建导致的问题

**Comment by bietiaop** [comment]
copilot 自动生成的，这个功能是没有的，之前发现了但是还没有删除，不影响正常使用。

**Comment by bietiaop** [comment]
哦好像没法保存是吧，我待会改一下

**Comment by Xbaishu** [comment]
> copilot 自动生成的，这个功能是没有的，之前发现了但是还没有删除，不影响正常使用。

是这样的，并且经过测试并不能使用%来作为命令前缀，因为机器人对此无反应
![image](https://github.com/user-attachments/assets/c7733822-d2ee-4180-99fe-533bbf0cb920)

**Comment by Xbaishu** [comment]
![image](https://github.com/user-attachments/assets/e505bf81-34fb-4d33-8d48-0f7479e1fb98)
以上为本人安装的所有插件，没有发现报错

**Comment by bietiaop** [comment]
中间不要有空格
