### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [ZZZure/ZZZ-Plugin#41]
![image](https://github.com/user-attachments/assets/02d1d9c0-3a22-4ceb-ba88-1f3edced571d)

**Comment by bietiaop** [comment]
你更新试试（

**Comment by S-t-e-v-e-e** [comment]
> 你更新试试（

ZZZ-Plugin已经是最新版本
最后更新时间：08-09 18:09

**Comment by S-t-e-v-e-e** [comment]
> > 你更新试试（
> 
> ZZZ-Plugin已经是最新版本 最后更新时间：08-09 18:09

能用了（
