### ISSUE TITLE
更新面板命令报错

### ISSUE THREAD

**Issue by Otaku-Liu** [ZZZure/ZZZ-Plugin#42]
![image](https://github.com/user-attachments/assets/1bbb2945-9d11-4d99-a011-73f32c254202)
日志如图，崩铁原神更新面板命令正常，米游社可以正常使用

**Comment by ZZZLE** [comment]
同款报错

**Comment by S-t-e-v-e-e** [comment]
试试重新绑下ck

**Comment by Otaku-Liu** [comment]
> 试试重新绑下ck

不行，刷新ck命令，用xiaoyao插件的扫码登陆命令都试过了

**Comment by bietiaop** [comment]
@kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。

**Comment by kissnavel** [comment]
> @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。

getfp其实就是类似这个功能

**Comment by kissnavel** [comment]
> @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。

getfp其实就是类似这个功能

**Comment by bietiaop** [comment]
> > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> 
> getfp其实就是类似这个功能

fp 好像不管用，还需要其他参数，不然就很容易出现这种报错

**Comment by kissnavel** [comment]
> > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > 
> > 
> > getfp其实就是类似这个功能
> 
> fp 好像不管用，还需要其他参数，不然就很容易出现这种报错

这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。

**Comment by kissnavel** [comment]
> > > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > > 
> > > 
> > > getfp其实就是类似这个功能
> > 
> > 
> > fp 好像不管用，还需要其他参数，不然就很容易出现这种报错
> 
> 这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。

![7becb3ffc81ea177aa5429eb2b73edb8](https://github.com/user-attachments/assets/5a9b5b73-b2d1-4aab-9c68-2ac8431449b3)
目前用自己号、其他人的号通过暴力测试仅触发1034、10035验证码，未触发5003、10041账号风险，账号在米游社的安全级别为中。
其他未测试的号中，有一人触发5003、10041账号风险，账号在米游社的安全级别为高，该账号在米游社app查询一切正常。
推测本周开始zzz加强检测，安全级别为高的账号会报5003、10041账号风险，目前无能为力。
本issue中各位账号在米游社的安全级别是什么？如安全级别为高，那么推测为上述问题。

**Comment by ZZZLE** [comment]
> > > > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > > > 
> > > > 
> > > > getfp其实就是类似这个功能
> > > 
> > > 
> > > fp 好像不管用，还需要其他参数，不然就很容易出现这种报错
> > 
> > 
> > 这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。
> 
> ![7becb3ffc81ea177aa5429eb2b73edb8](https://private-user-images.githubusercontent.com/53962152/356875399-5a9b5b73-b2d1-4aab-9c68-2ac8431449b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODM4MTYsIm5iZiI6MTcyMzM4MzUxNiwicGF0aCI6Ii81Mzk2MjE1Mi8zNTY4NzUzOTktNWE5YjViNzMtYjJkMS00YWFiLTljNjgtMmFjODQzMTQ0OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEzMzgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNDQ0YzkzZmM3MWEyMzliZWNjYjdmYmZjMjkxOGI2ZmY2OWVhYmU4YjM3NTQxOTM3ZTkzYjAyNzRhMTI0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDt2M8H0L3WWDybHpymfKq9tD0TPcYgtttpQ7sKXf0Y) 目前用自己号、其他人的号通过暴力测试仅触发1034、10035验证码，未触发5003、10041账号风险，账号在米游社的安全级别为中。 其他未测试的号中，有一人触发5003、10041账号风险，账号在米游社的安全级别为高，该账号在米游社app查询一切正常。 推测本周开始zzz加强检测，安全级别为高的账号会报5003、10041账号风险，目前无能为力。 本issue中各位账号在米游社的安全级别是什么？如安全级别为高，那么推测为上述问题。

![QQ20240811-214120](https://github.com/user-attachments/assets/91994019-2125-48bb-9a49-e349a21242b6)
我的报10041，账号确实安全等级为高

**Comment by ZZZLE** [comment]
> > > > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > > > 
> > > > 
> > > > getfp其实就是类似这个功能
> > > 
> > > 
> > > fp 好像不管用，还需要其他参数，不然就很容易出现这种报错
> > 
> > 
> > 这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。
> 
> ![7becb3ffc81ea177aa5429eb2b73edb8](https://private-user-images.githubusercontent.com/53962152/356875399-5a9b5b73-b2d1-4aab-9c68-2ac8431449b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODQ3MjIsIm5iZiI6MTcyMzM4NDQyMiwicGF0aCI6Ii81Mzk2MjE1Mi8zNTY4NzUzOTktNWE5YjViNzMtYjJkMS00YWFiLTljNjgtMmFjODQzMTQ0OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEzNTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzQ1MDFhOTg5YjYwZTViYzIwMmMyM2NiYjU2NDBjMDg5MTE4NWRhOWVkOGE3NzJhZTU2NGViZjU5YTc5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kkq-O-pl6DlycLVTxv4TN067euSHMy7m7d7fSIOUO8I) 目前用自己号、其他人的号通过暴力测试仅触发1034、10035验证码，未触发5003、10041账号风险，账号在米游社的安全级别为中。 其他未测试的号中，有一人触发5003、10041账号风险，账号在米游社的安全级别为高，该账号在米游社app查询一切正常。 推测本周开始zzz加强检测，安全级别为高的账号会报5003、10041账号风险，目前无能为力。 本issue中各位账号在米游社的安全级别是什么？如安全级别为高，那么推测为上述问题。

![JIETU_24-08-11_215220](https://github.com/user-attachments/assets/697a1180-bf60-4659-bcf5-dab749d94303)
![1E741C43DEC0DDE60B20096FE9938813](https://github.com/user-attachments/assets/5accae59-0c51-4a45-9100-523036e5c52e)
安全等级为高的不一定会触发10041，我账号安全等级为高，触发了10041，但是同样的ck发给某个机器人却不会触发10041的问题

**Comment by kissnavel** [comment]
> > > > > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > > > > 
> > > > > 
> > > > > getfp其实就是类似这个功能
> > > > 
> > > > 
> > > > fp 好像不管用，还需要其他参数，不然就很容易出现这种报错
> > > 
> > > 
> > > 这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。
> > 
> > 
> > ![7becb3ffc81ea177aa5429eb2b73edb8](https://private-user-images.githubusercontent.com/53962152/356875399-5a9b5b73-b2d1-4aab-9c68-2ac8431449b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODQ3MjIsIm5iZiI6MTcyMzM4NDQyMiwicGF0aCI6Ii81Mzk2MjE1Mi8zNTY4NzUzOTktNWE5YjViNzMtYjJkMS00YWFiLTljNjgtMmFjODQzMTQ0OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEzNTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzQ1MDFhOTg5YjYwZTViYzIwMmMyM2NiYjU2NDBjMDg5MTE4NWRhOWVkOGE3NzJhZTU2NGViZjU5YTc5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kkq-O-pl6DlycLVTxv4TN067euSHMy7m7d7fSIOUO8I) 目前用自己号、其他人的号通过暴力测试仅触发1034、10035验证码，未触发5003、10041账号风险，账号在米游社的安全级别为中。 其他未测试的号中，有一人触发5003、10041账号风险，账号在米游社的安全级别为高，该账号在米游社app查询一切正常。 推测本周开始zzz加强检测，安全级别为高的账号会报5003、10041账号风险，目前无能为力。 本issue中各位账号在米游社的安全级别是什么？如安全级别为高，那么推测为上述问题。
> 
> ![JIETU_24-08-11_215220](https://private-user-images.githubusercontent.com/70804803/356882450-697a1180-bf60-4659-bcf5-dab749d94303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODY1NzAsIm5iZiI6MTcyMzM4NjI3MCwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI0NTAtNjk3YTExODAtYmY2MC00NjU5LWJjZjUtZGFiNzQ5ZDk0MzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTgxZDEzNjU1M2FiNDg5OGY2M2JjYjQwMTMxODljNzYwNDQyMzcwOGVhMDhjY2VjOWFhYzE0M2VlYzU3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1T1HZ7PUeRPYjrXi6aHdvFRaWYrij6h1pjMiTEp5MPA) ![1E741C43DEC0DDE60B20096FE9938813](https://private-user-images.githubusercontent.com/70804803/356882454-5accae59-0c51-4a45-9100-523036e5c52e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODY1NzAsIm5iZiI6MTcyMzM4NjI3MCwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI0NTQtNWFjY2FlNTktMGM1MS00YTQ1LTkxMDAtNTIzMDM2ZTVjNTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZTk5N2FkYjkxOGE0ZmJlMTUzZDg0ZDM5YTk1MTFjYWU4ZWFhYjdkMWRlM2E3ODYyNjdhNzk5MDhhMzBiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uT2O33awTZbcOXFVJbYzcpJY2lCmDKvV36UuR8WbkGE) ↑这是群友的
> 
> ![QQ20240811-220230](https://private-user-images.githubusercontent.com/70804803/356882989-ad15ecc2-1192-43f5-951f-9d1fa7e65365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODY1NzAsIm5iZiI6MTcyMzM4NjI3MCwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5ODktYWQxNWVjYzItMTE5Mi00M2Y1LTk1MWYtOWQxZmE3ZTY1MzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NTM5YTM2MGQ1YzcyYTk3OTYzOWQxNjEzY2Q4NTEwOTg0YmQ3MjA4ZjA3MmYwZjE5NjIwNDY3NjRiNzhlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VwZvZKSjy8aWJwK_zaBW7KePxCkX65YUSDl9nc_ljx8) ![QQ20240811-220314](https://private-user-images.githubusercontent.com/70804803/356882986-be50aa7c-6ff1-4bd9-83bd-379c7c36ac74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODY1NzAsIm5iZiI6MTcyMzM4NjI3MCwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5ODYtYmU1MGFhN2MtNmZmMS00YmQ5LTgzYmQtMzc5YzdjMzZhYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjE2OWUzNGM4Yjk1NmU5YmEwZmFlMWU2MmZlN2VkODBiMTBjY2I4ZjkzOWU4MTQ3NmNiYTlmNWU2N2UwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f6xNmjkH0PHPqVEKSz_Mh2veLasUuGTlvkGr2qZQZDc) ![QQ20240811-220209](https://private-user-images.githubusercontent.com/70804803/356882991-5cb6c884-add0-4cef-964d-f5783a937edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODY1NzAsIm5iZiI6MTcyMzM4NjI3MCwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5OTEtNWNiNmM4ODQtYWRkMC00Y2VmLTk2NGQtZjU3ODNhOTM3ZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MDE1OWYyOGUzYTg5NDMzZTMyYWFkNmM5OWU1NjAzNjZlYjZmY2QzMjQ0OGQ4NjJmM2EyMDhiNWQzOGUxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dsqSB1fiXo_s6BQjlxRIPHj1V8hHGyy0zfcTsxx0DFQ) ↑这是我的 安全等级为高的不一定会触发10041，我账号安全等级为高，触发了10041，但是同样的ck发给某个机器人却不会触发10041的问题

如果两个bot本体和插件都是最新仅ip不同，推测mys判断账号访问接口的ip有问题报5003、10041账号风险，未报1034、10035验证码从而无法过码。

**Comment by kissnavel** [comment]
目前发现此类报5003、10041的账号在其他渠道（例如小程序）查询时同样有概率因账号风险而无法查询，目前无能为力。

**Comment by Otaku-Liu** [comment]
> 目前发现此类报5003、10041的账号在其他渠道（例如小程序）查询时同样有概率因账号风险而无法查询，目前无能为力。

好的，谢谢，辛苦了

**Comment by kissnavel** [comment]
关联#45

**Comment by devil233-ui** [comment]
> > > > > > @kissnavel 你看看可以加一个绑定设备功能么，类似于gscore的。
> > > > > 
> > > > > 
> > > > > getfp其实就是类似这个功能
> > > > 
> > > > 
> > > > fp 好像不管用，还需要其他参数，不然就很容易出现这种报错
> > > 
> > > 
> > > 这个就是少部分账号构建的fp没过账号检测，判断异常了。理想状态fp不过测是报1034、10035然后调用过码，但现在这些少部分fp没过测的账号中有些会报5003、10041，这两个代码是没有验证码的。
> > 
> > 
> > ![7becb3ffc81ea177aa5429eb2b73edb8](https://private-user-images.githubusercontent.com/53962152/356875399-5a9b5b73-b2d1-4aab-9c68-2ac8431449b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODQ3MjIsIm5iZiI6MTcyMzM4NDQyMiwicGF0aCI6Ii81Mzk2MjE1Mi8zNTY4NzUzOTktNWE5YjViNzMtYjJkMS00YWFiLTljNjgtMmFjODQzMTQ0OWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDEzNTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzQ1MDFhOTg5YjYwZTViYzIwMmMyM2NiYjU2NDBjMDg5MTE4NWRhOWVkOGE3NzJhZTU2NGViZjU5YTc5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kkq-O-pl6DlycLVTxv4TN067euSHMy7m7d7fSIOUO8I) 目前用自己号、其他人的号通过暴力测试仅触发1034、10035验证码，未触发5003、10041账号风险，账号在米游社的安全级别为中。 其他未测试的号中，有一人触发5003、10041账号风险，账号在米游社的安全级别为高，该账号在米游社app查询一切正常。 推测本周开始zzz加强检测，安全级别为高的账号会报5003、10041账号风险，目前无能为力。 本issue中各位账号在米游社的安全级别是什么？如安全级别为高，那么推测为上述问题。
> 
> ![JIETU_24-08-11_215220](https://private-user-images.githubusercontent.com/70804803/356882450-697a1180-bf60-4659-bcf5-dab749d94303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY1MzIsIm5iZiI6MTcyMzcyNjIzMiwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI0NTAtNjk3YTExODAtYmY2MC00NjU5LWJjZjUtZGFiNzQ5ZDk0MzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYTdjNmZiZDU2ZjMxNTFhMWIxNDJlYzllMGQyMzgzMjkxNGM5MTEyNTlhYTBhZTAwNmUxZGI5ZmY3YTMxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DcflblmikYiQbRZDN_w6rKyjVEJGiUl4QdxG3byiAgY) ![1E741C43DEC0DDE60B20096FE9938813](https://private-user-images.githubusercontent.com/70804803/356882454-5accae59-0c51-4a45-9100-523036e5c52e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY1MzIsIm5iZiI6MTcyMzcyNjIzMiwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI0NTQtNWFjY2FlNTktMGM1MS00YTQ1LTkxMDAtNTIzMDM2ZTVjNTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNzk5MjA2OGQ2MzQ2ZGQ2MjBlMTUxMjI3OTYyOWM2MDc5YzVmOTQyMDQ5ZWMyZmNjM2U3ZDY4Mzc3MGJkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WMeaLeZTHwS5BY5lzYlY3IQUX3qzr7vJzgCqmV60-k8) ↑这是群友的
> 
> ![QQ20240811-220230](https://private-user-images.githubusercontent.com/70804803/356882989-ad15ecc2-1192-43f5-951f-9d1fa7e65365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY1MzIsIm5iZiI6MTcyMzcyNjIzMiwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5ODktYWQxNWVjYzItMTE5Mi00M2Y1LTk1MWYtOWQxZmE3ZTY1MzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjEwMTFhYTc1ZWY0NGY2ZTI5M2M2N2FhNjhmN2QzMzkxZDA4MWI0NTgxNDBkMGE0YTcxNmE2YTM3ZDRlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OV4tIyqu62Qx5AiTRw2cFs-oO0vMITiLKiJE-6oE0Ow) ![QQ20240811-220314](https://private-user-images.githubusercontent.com/70804803/356882986-be50aa7c-6ff1-4bd9-83bd-379c7c36ac74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY1MzIsIm5iZiI6MTcyMzcyNjIzMiwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5ODYtYmU1MGFhN2MtNmZmMS00YmQ5LTgzYmQtMzc5YzdjMzZhYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMWI4ZjM3OGE2ZmM0OTMwNTExNDc5MzMwZjJiY2VlNGZlZDYxOGE4MTg0MWUyNDY1YTVkMGM4NzE1ZDM3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XzkHeucgeAeoS8lNpBIIWbO4D0QgJXHlJahu5yT0Fkg) ![QQ20240811-220209](https://private-user-images.githubusercontent.com/70804803/356882991-5cb6c884-add0-4cef-964d-f5783a937edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjY1MzIsIm5iZiI6MTcyMzcyNjIzMiwicGF0aCI6Ii83MDgwNDgwMy8zNTY4ODI5OTEtNWNiNmM4ODQtYWRkMC00Y2VmLTk2NGQtZjU3ODNhOTM3ZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEyNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMTZhMTg1NTlkY2IyYTRiNzYwNjAzZDAyYzQxODRmNWFjZjUwZjcxNjU0ODFhMWI4ZjAxNjhiZWZmN2Q2YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JD5Nck1a9REQQV4Kw4gHfeeaXN_kx8ZJxvajgN6G7ek) ↑这是我的 安全等级为高的不一定会触发10041，我账号安全等级为高，触发了10041，但是同样的ck发给某个机器人却不会触发10041的问题

和你完全一样的情况，只能先蹭其他bot了...

**Comment by bietiaop** [comment]
@kissnavel 加一下我QQ，测一下设备绑定，需要手机可以抓包。

**Comment by kissnavel** [comment]
> @kissnavel 加一下我QQ，测一下设备绑定，需要手机可以抓包。

多少？我加你

**Comment by bietiaop** [comment]
> > @kissnavel 加一下我QQ，测一下设备绑定，需要手机可以抓包。
> 
> 多少？我加你

1527109126

**Comment by bietiaop** [comment]
已解决，绑定设备即可。
