### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by 8852690** [ZZZure/ZZZ-Plugin#44]
![image](https://github.com/user-attachments/assets/ea08c80b-f26f-4183-be07-915d4a81260d)
Emmm...刚尝试了删除重新clone也是一样的问题

**Comment by bietiaop** [comment]
请我问题还存在吗

**Comment by 8852690** [comment]
> 请我问题还存在吗

我刚更新了一下，问题依旧存在.
![image](https://github.com/user-attachments/assets/0ffea179-fa28-4ac7-b543-2b0909ed732a)
![image](https://github.com/user-attachments/assets/f23708ac-0093-424f-b15d-7fbc2840251b)

**Comment by bietiaop** [comment]
你的 nodejs 版本是多少呢

**Comment by bietiaop** [comment]
更新或者重新弄一下 yunzai 本体呢 这像是 yunzai 出的问题

**Comment by 8852690** [comment]
> 更新或者重新弄一下 yunzai 本体呢 这像是 yunzai 出的问题

喵崽本体我是保持的最新状态，node版本18.20.1

**Comment by bietiaop** [comment]
升级 node 版本至 20 及以上试试

**Comment by bietiaop** [comment]
加一下 readme 里面的 QQ群在群里说方便

**Comment by 8852690** [comment]
> 升级 node 版本至 20 及以上试试

明天我试下，毕竟18还在官方维护期内，所以之前一直没切版本

**Comment by 8852690** [comment]
> 升级 node 版本至 20 及以上试试

刚升级到20.16.0，仍存在这个问题
![image](https://github.com/user-attachments/assets/98bd413f-bd24-4f63-9437-be1d3e2267c1)

**Comment by bietiaop** [comment]
加一下群看看，我觉得可能是崽的问题

**Comment by 8852690** [comment]
> 加一下群看看，我觉得可能是崽的问题

加了2-3次了，不知道是不是进已过滤里面了

**Comment by 8852690** [comment]
刚在本地测试加载未出现异常，疑似服务器环境问题，工单结束。
