### ISSUE TITLE
体力、更新面板、查看防卫战都在报错

### ISSUE THREAD

**Issue by zdx2473788063** [ZZZure/ZZZ-Plugin#45]
![58d353a4-e933-4cbf-b6d5-ae04e8be1bf7](https://github.com/user-attachments/assets/29469e9e-a709-49f4-99cb-86cd6cd9eceb)

**Comment by kissnavel** [comment]
详见#42
疑似上周开始加强检测，目前部分账号所有访问接口的都有概率不报1034、10035验证码而是报5003、10041账号异常，目前无能为力。

**Comment by china-silence-chen** [comment]
能修吗

**Comment by bietiaop** [comment]
通过绑定设备即可
