### ISSUE TITLE
绑定设备后，更新面板依旧账号异常

### ISSUE THREAD

**Issue by Otaku-Liu** [ZZZure/ZZZ-Plugin#46]
日志如图
![image](https://github.com/user-attachments/assets/faed750b-2da4-4c73-abfa-e0e012c7ae6f)
是否需要提供设备信息或者指定的字段呢？

**Comment by bietiaop** [comment]
绑定设备会概率性解决 10041 并不是保证 100% 解决

**Comment by bietiaop** [comment]
再多试两次呢

**Comment by Otaku-Liu** [comment]
> 再多试两次呢

大概绑了3次了吧总共，我再让他试试

**Comment by bietiaop** [comment]
他绑定的设备参数里有没有 oaid 呢

**Comment by Otaku-Liu** [comment]
> 他绑定的设备参数里有没有 oaid 呢

有的

**Comment by bietiaop** [comment]
建议使用第三方插件过。这是米游社针对 bot 做的限制。绑定设备只是尝试解决，并非一定解决。

**Comment by devil233-ui** [comment]
> 建议使用第三方插件过。这是米游社针对 bot 做的限制。绑定设备只是尝试解决，并非一定解决。

请问第三方插件指的是？
目前通过绑定设备解决了面板问题，但仍无法查询体力
![image](https://github.com/user-attachments/assets/2d26cd50-70ee-4d94-bda6-9c4c75675201)
