### ISSUE TITLE
%下载全部资源/%XXX面板没有效果

### ISSUE THREAD

**Issue by LeiSureLyYrsc** [ZZZure/ZZZ-Plugin#48]
%更新面板 后可以正常出现面板图
但发送%XXX面板 后只有
_查询成功，正在下载图片资源，请稍候。_
的回复，没有出角色资料图
↑重装后输出面板只出一次后面就不出了
%下载全部资源 等待了10分钟没有结果

我访问过mystool里面api.js的部分API，是正常的404 Not Found界面
（网络环境是家宽，应该没有被API封禁IP）

系统:Windows Server 2022 DataCenter
Node.js版本:22.2.0
Miao-Yunzai

**Comment by bietiaop** [comment]
已修复
