### ISSUE TITLE
能不能适配一下云崽常用习惯指令

### ISSUE THREAD

**Issue by qpdbzzz** [ZZZure/ZZZ-Plugin#5]
便签 - 命令: #zzznote、%note
%体力
基本信息汇总 - 命令: #zzzcard、%card
%角色
更新抽卡记录（需要逍遥插件支持） - 命令: #zzz
刷新抽卡链接、%刷新抽卡链接
%刷新抽卡记录
抽卡记录 - 命令: #zzz抽卡分析、%抽卡分析
%抽卡记录

**Comment by Denfenglai** [comment]
可能是考虑到崽后续会出同样的功能所以才这么写的吧
喵崽现已有`%体力`

**Comment by bietiaop** [comment]
加上吧

**Comment by bietiaop** [comment]
已添加。因为插件三天完成的，并没有考虑到指令选择，如果有什么建议可以提issue或者到群里进行反馈。
