### ISSUE TITLE
无法查看简的面板

### ISSUE THREAD

**Issue by GenePaimon** [ZZZure/ZZZ-Plugin#68]
先使用了“%更新面板”命令获取到了简和塞斯的面板数据，
然后使用命令“%简面板”时，返回“未找到角色简的面板信息，请先刷新面板”
查看塞斯的面板则没有此问题
![image](https://github.com/user-attachments/assets/e15fbb80-8cd3-48c2-9b80-fb05324c593e)

**Comment by bietiaop** [comment]
更新插件了吗

**Comment by Fwindy** [comment]
> 更新插件了吗

我看到插件的更新提示以为已经更新了，原来只是个提示，乌龙了
关闭了

**Comment by GenePaimon** [comment]
> 更新插件了吗

我把插件的更新提示当成已更新了，原来只是个提示，乌龙了
