### ISSUE TITLE
%体力报错 米游社账号异常，暂时无法查询 绑定设备也没用 其他更新抽卡记录都可以使用

### ISSUE THREAD

**Issue by xiaxin230** [ZZZure/ZZZ-Plugin#73]
![09D8BC8BC48D1179C53BEC8EC52FDB3C](https://github.com/user-attachments/assets/f89928f0-a308-4bcf-957a-f5ba038f46c3)
![1cbf0ee5-a4ed-4473-8d77-8a8400a5ab61](https://github.com/user-attachments/assets/b5ecd9e4-4f23-452c-92c9-71925b69855e)

**Comment by xiaxin230** [comment]
改过密码 也没用

**Comment by xiaxin230** [comment]
> 改过密码 也没用

%更新面板 也报错 无法使用

**Comment by lin-junliang** [comment]
看看这个米游社账号有没有原神uid

**Comment by kissnavel** [comment]
解绑设备然后按照readme改用默认设备信息看下
设备信息并不能100%解决账号异常

**Comment by xiaxin230** [comment]
> 解绑设备然后按照readme改用默认设备信息看下 设备信息并不能100%解决账号异常
![image](https://github.com/user-attachments/assets/5e0bbf8e-9dfc-48e6-ac1c-d9d30f7ac4f4)
an按这个设置过 也还是异常

**Comment by kissnavel** [comment]
> > 解绑设备然后按照readme改用默认设备信息看下 设备信息并不能100%解决账号异常
> > ![image](https://private-user-images.githubusercontent.com/51977135/367506178-5e0bbf8e-9dfc-48e6-ac1c-d9d30f7ac4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDg1NTcsIm5iZiI6MTcyNjMwODI1NywicGF0aCI6Ii81MTk3NzEzNS8zNjc1MDYxNzgtNWUwYmJmOGUtOWRmYy00OGU2LWFjMWMtZDlkMzBmN2FjNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEwMDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWFkOWQxM2Q4YzliZTljZWI3MjlmY2VjYTJjNTJmMWQzNWU3ZTdmYzc3NTU2ZTJjMTU1YmI1MTIwMzk2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMod79154UFKhkPApjIUZZYbz_Vg2qS1ZD51AS4r4KI)
> > an按这个设置过 也还是异常

删除配置文件重启，改用插件自带的
