### ISSUE TITLE
周一开始又出现了米游社账号异常

### ISSUE THREAD

**Issue by china-silence-chen** [ZZZure/ZZZ-Plugin#74]
出了绑定设备之后，一直正常了。但是周一开始突然账号异常了，然后重新扫码登陆，重新绑定设备都没有用了。

**Comment by china-silence-chen** [comment]
群里好几个都是这样的情况，突然出现的

**Comment by kissnavel** [comment]
用的最新的commit吗？试下解绑设备后用默认设备参数

**Comment by china-silence-chen** [comment]
> 用的最新的commit吗？试下解绑设备后用默认设备参数

试过了，重新扫码登陆，解绑设备，直接更新都试过了，都是报米游社账号异常

**Comment by kissnavel** [comment]
> > 用的最新的commit吗？试下解绑设备后用默认设备参数
> 
> 试过了，重新扫码登陆，解绑设备，直接更新都试过了，都是报米游社账号异常。 代码就更新的最新的，显示已经是最新版本

回退到之前的commit报不报账号异常？

**Comment by kissnavel** [comment]
绑定设备已回退修改，更新后看下是否正常
绑定设备并不是100%解决账号异常

**Comment by china-silence-chen** [comment]
> 绑定设备已回退修改，更新后看下是否正常 绑定设备并不是100%解决账号异常

好了，刚更新了一下，群里好几个人都恢复了，可以查了，感谢
