### ISSUE TITLE
话说有考虑做国际服适配吗

### ISSUE THREAD

**Issue by NRZ091** [ZZZure/ZZZ-Plugin#79]
如题

**Comment by kissnavel** [comment]
插件本身就支持国际服使用啊，目前只有抽卡记录相应功能不支持国际服，网络问题需自行解决。

**Comment by kissnavel** [comment]
另外国际服不需要绑定设备，所以这个也没有

**Comment by NRZ091** [comment]
> 插件本身就支持国际服使用啊，目前只有抽卡记录相应功能不支持国际服，网络问题需自行解决。

好的，昨天因为插件的使用需要绑定ck，二维码登录用多了，hoyolab没有扫码功能想当然的的以为插件不适配国际服了
目前已经通过vIa获取ck了
