### ISSUE TITLE
一发指令就会把微信协议comWechat给干掉

### ISSUE THREAD

**Issue by www48055** [ZZZure/ZZZ-Plugin#80]
一发指令就会把微信协议comWechat给干掉，之前是不会的

**Comment by kissnavel** [comment]
协议端问题，图片太大发不了会卡死重启，配置文件里分辨率调低。

**Comment by www48055** [comment]
确实是这个问题，精度调了50能正常用了，就是图片比较糊

**Comment by www48055** [comment]
确实是这个问题，精度调了50能正常用了，就是图片比较糊
