### ISSUE TITLE
面板渲染图片错误

### ISSUE THREAD

**Issue by youbai520** [ZZZure/ZZZ-Plugin#82]
用的是trss崽，插件和崽都更新过了
命令“%11号面板”
命令行输出
![Screenshot_2024-12-13-19-46-06-32_3d419158bad5872c40592a6c9956e692](https://github.com/user-attachments/assets/d23a30e1-0350-49a4-b3c2-1041380be0f9)
输出在群里面的图片
![Image_1734090433859](https://github.com/user-attachments/assets/a0b091c2-1071-4a1d-ac71-50863bc9efd4)

**Comment by youbai520** [comment]
已经尝试过%删除全部资源，%下载全部资源，也重装过崽的依赖，依旧没解决，但是%更新面板的图片是正常的

**Comment by bietiaop** [comment]
你的node版本是多少

**Comment by youbai520** [comment]
node版本22.3.0
![Screenshot_2024-12-14-13-04-30-51_3d419158bad5872c40592a6c9956e692](https://github.com/user-attachments/assets/740bca40-f4f4-4045-a528-78436068d65a)

**Comment by bietiaop** [comment]
这个报错是Redis的报错，跟面板图显示没有关系，你截图一下~/Miao-Yunzai/plugins/ZZZ-Plugin/resources/images里面看看，是不是缺少文件

**Comment by youbai520** [comment]
![Screenshot_2024-12-14-23-14-25-06_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/278f6c38-161f-4f97-9e14-8aa2889a42a4)
![Screenshot_2024-12-14-23-14-14-45_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/badd9ef6-59b7-4d12-8dc4-4d7e5903a1b1)
![Screenshot_2024-12-14-23-13-48-00_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/706cebc6-c2aa-4443-8ca6-c7def9a0589e)
我现在QQ里面使用了删除所有资源和下载所有资源的命令再截得的文件夹图，数量好像是对不上，但是在QQ里面说下载都是成功的

**Comment by youbai520** [comment]
我截取了部分“%下载所有资源”命令的日志，应该是连接不上下载节点，
![Screenshot_2024-12-14-23-33-40-92_3d419158bad5872c40592a6c9956e692](https://github.com/user-attachments/assets/824603af-0a50-46d1-a9ad-2da4a19705ea)

**Comment by bietiaop** [comment]
可能是图片资源服务器出现了问题 可能需要等等

**Comment by bietiaop** [comment]
在 commit `4faa961` 修复了。

**Comment by youbai520** [comment]
感谢佬的帮助，已经正常了
