### ISSUE TITLE
音擎图片资源均无法显示

### ISSUE THREAD

**Issue by Damnlt** [ZZZure/ZZZ-Plugin#83]
![image](https://github.com/user-attachments/assets/7bdef367-665f-4eda-b9c6-deec0ae4018b)
已尝试过很多次 ``%删除所有资源`` 再查看
 均无效, FBI布的头像资源错乱 显示的是赤红布

**Comment by bietiaop** [comment]
更新一下插件先

**Comment by Damnlt** [comment]
> 更新一下插件先

感谢，更新完音擎资源好了，邦布的那个问题还在

**Comment by devil233-ui** [comment]
邦布主要是fbi布头像显示成外环猪了吧
