### ISSUE TITLE
【bug】邦布头像错误

### ISSUE THREAD

**Issue by mengluo04** [ZZZure/ZZZ-Plugin#84]
根据代码和抽卡记录里面的id，拼接出来的邦布头像URL是这个
https://act-webstatic.mihoyo.com/game_record/zzzv2/bangboo_rectangle_avatar/bangboo_rectangle_avatar_54014.png
这个id是最新的【探员】邦布的item_id，显示是猪鼻子那个

**Comment by bietiaop** [comment]
没看懂，是米游社返回的图片错了还是id拼接错了？

**Comment by mengluo04** [comment]
> 没看懂，是米游社返回的图片错了还是id拼接错了？

返回的图片错了，米游社里面看是这个
![image](https://github.com/user-attachments/assets/7bfb4ebd-e895-4c7f-bafd-5bcbfe0cd4d9)
这是抽卡记录里面的数据
```json
    {
      "uid": "16202519",
      "gacha_id": "0",
      "gacha_type": "5",
      "item_id": "54014",
      "count": "1",
      "time": "2024-12-18 10:35:35",
      "name": "格列佛探员",
      "lang": "zh-cn",
      "item_type": "邦布",
      "rank_type": "4",
      "id": "1734487200039353519",
      "square_icon": ""
    },
```

**Comment by youbai520** [comment]
![image](https://github.com/user-attachments/assets/84630fb0-87c5-44c0-a7c4-e933ac352759)
我在资源文件里面里面看着这两个邦布图片是一样的，删了重新下的资源也一样

**Comment by youbai520** [comment]
> 没看懂，是米游社返回的图片错了还是id拼接错了？

是图片资源的文件错误
![image](https://github.com/user-attachments/assets/93c9d9b2-f213-4ed1-8586-b4b4896aa1fb)

**Comment by bietiaop** [comment]
等一两天

**Comment by jiuyixian** [comment]
着急可自行替换

邦布图片路径：/ZZZ-Plugin/resources/images/bangboo_square_avatar
命名：bangboo_rectangle_avatar_54014.png
原图+效果图
![bangboo_rectangle_avatar_54014](https://github.com/user-attachments/assets/34e3598d-016b-4d7f-bcae-08ae23f8e69b)
![效果1](https://github.com/user-attachments/assets/88194dc0-e5cd-4f9a-951f-1ef579cf7197)
裁剪图+效果图
![bangboo_rectangle_avatar_54014](https://github.com/user-attachments/assets/a2aa2b24-cba0-4eb7-b695-0759cec6b9b6)
![效果2](https://github.com/user-attachments/assets/afe646f8-caf1-45d4-bf3a-633635066880)

**Comment by mengluo04** [comment]
> 着急可自行替换
> 
> 邦布图片路径：/ZZZ-Plugin/resources/images/bangboo_square_avatar 命名：bangboo_rectangle_avatar_54014.png 原图+效果图 ![bangboo_rectangle_avatar_54014](https://private-user-images.githubusercontent.com/147913992/397276762-34e3598d-016b-4d7f-bcae-08ae23f8e69b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTU2NDEsIm5iZiI6MTczNDU5NTM0MSwicGF0aCI6Ii8xNDc5MTM5OTIvMzk3Mjc2NzYyLTM0ZTM1OThkLTAxNmItNGQ3Zi1iY2FlLTA4YWUyM2Y4ZTY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwODAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDAxZDQ0OTRlZjI1MjIxZTU3ZTg2MWI3NDQyZDA4MzJjM2ZjNTYyYWY4OTBlYTdlNWU2ZjVjMDRmNDZhZjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8kUnd4Eze6qGnWPij9jAWj8ScMNN6Gw_OnX5PelwKDU) ![效果1](https://private-user-images.githubusercontent.com/147913992/397276767-88194dc0-e5cd-4f9a-951f-1ef579cf7197.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTU2NDEsIm5iZiI6MTczNDU5NTM0MSwicGF0aCI6Ii8xNDc5MTM5OTIvMzk3Mjc2NzY3LTg4MTk0ZGMwLWU1Y2QtNGY5YS05NTFmLTFlZjU3OWNmNzE5Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwODAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzNjNThkMWQ4YjQyYzAzNDQ4MzM0MDM2MmNiZjlmYTEyZTY0ZGRhMDIxYzBkNjlhMDQzZWMxOTg1MGUyYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aWRO9gGqPLt0Axk9NauvHe67mjF4qzqilHjSso0Ody4) 裁剪图+效果图 ![bangboo_rectangle_avatar_54014](https://private-user-images.githubusercontent.com/147913992/397276783-a2aa2b24-cba0-4eb7-b695-0759cec6b9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTU2NDEsIm5iZiI6MTczNDU5NTM0MSwicGF0aCI6Ii8xNDc5MTM5OTIvMzk3Mjc2NzgzLWEyYWEyYjI0LWNiYTAtNGViNy1iNjk1LTA3NTljZWM2YjliNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwODAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGIyODdlZWRlMmY5ZTYwMGFkMDAyMjkyNzdjYTg5MTgxMWU2ZDk1OGU2NmU1NmFlYzYxZDZhZTg4ODc1ZTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pp--tXWqgoXtzpA379Q6c_UzWlL637xEjrxQX4GrXc0) ![效果2](https://private-user-images.githubusercontent.com/147913992/397276806-afe646f8-caf1-45d4-bf3a-633635066880.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTU2NDEsIm5iZiI6MTczNDU5NTM0MSwicGF0aCI6Ii8xNDc5MTM5OTIvMzk3Mjc2ODA2LWFmZTY0NmY4LWNhZjEtNDVkNC1iZjNhLTYzMzYzNTA2Njg4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwODAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmYzMjM1ZDQxZGRjYTNkNmU3NmM2MzQ5NTA1ZjkxYjdiYjM5MWI4NDVhMTcyZjg5ODc1OTg3MWYxOTIyOGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ob9VHsuCzJionwgrFAy1G7IE8hNyI6r4PIl2DE7cRV0)

不着急，等大佬有空修复

**Comment by KimigaiiWuyi** [comment]
> 等一两天

已上传至CDN @bietiaop 
目标路径参考如下
http://tw-taipei-1.lcf.icu:20532/ZZZeroUID/resource/square_bangbo/bangboo_rectangle_avatar_54014.png

https://github.com/ZZZure/ZZZeroUID/commit/a3c4762a4539fb01e70e5ad1d633241cd2c8d0a1

**Comment by bietiaop** [comment]
收到，sir

**Comment by bietiaop** [comment]
@mengluo04 更新一下插件，执行 `%删除全部资源` 后 `%下载全部资源` 试试。

**Comment by mengluo04** [comment]
> @mengluo04 更新一下插件，执行 `%删除全部资源` 后 `%下载全部资源` 试试。

执行了，没生效。把`/ZZZ-Plugin/resources/images/bangboo_square_avatar`里面的图片删了重新`%抽卡记录`然后下载的图片也是那个猪头，看了代码的修改记录，先去cdn查，没有再去下载mys的，是cdn那边缓存还没更新吗

**Comment by bietiaop** [comment]
你能看到下载的完整路径吗 发来看看

**Comment by mengluo04** [comment]
> 你能看到下载的完整路径吗 发来看看

刚才重新看了下好像正常了，尝试加了个console.log没看到日志，不知道是不是加错地方了

**Comment by bietiaop** [comment]
云崽的控制台输出是logger.info、logger.mark、logger.debug这种的

**Comment by mengluo04** [comment]
> 云崽的控制台输出是logger.info、logger.mark、logger.debug这种的

我看是js的，直接用console了，尴尬。能获取到正确图片就不重要了

**Comment by devil233-ui** [comment]
> @mengluo04 更新一下插件，执行 `%删除全部资源` 后 `%下载全部资源` 试试。

重下后正常了，不过这个输出是不是需要改下？（指邦布头像其实可以正常下载
![image](https://github.com/user-attachments/assets/13850387-7800-4341-b0b4-0aa837c8a706)

~~还是说我哪里理解错了~~

**Comment by bietiaop** [comment]
确实不支持。下载的资源是没有邦布头像的，邦布头像是现查现下的。
